#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

deb_install () {
	echo installing git, kitty, zsh, nala, firefox, nvim, Latex, Discord, ranger, flameshot, timeshift
    read -p "install? [Y/n] " doit
    if [[ $doit = '' || $doit = 'y' || $doit = 'Y' ]]; then
        echo starting install...
    else
        echo exit
        exit
    fi

    read -p "password: " pass

	# basic startup
    echo -e "${GREEN}updating and upgrading${ENDCOLOR}"
	echo $pass | sudo apt -y update
	sudo apt -y upgrade
	rm -rf Templates/ Desktop/ Music/ Videos/
	mkdir Installs cs

	# git
    echo -e "${GREEN}installing git${ENDCOLOR}"
	sudo apt install -y git make
	git clone https://github.com/agmui/dotFiles.git

	# kitty
    echo -e "${GREEN}installing kitty${ENDCOLOR}"
	sudo apt -y install kitty
	mkdir $HOME/.config/kitty
	cp $HOME/dotFiles/kitty.conf $HOME/.config/kitty/kitty
	cd $HOME

    : '
	# zsh
    echo -e "${GREEN}installing zsh${ENDCOLOR}"
	sudo apt install -y zsh
    echo -e "${GREEN}input pass${ENDCOLOR}"
	sudo chsh -s $(which zsh)
	chsh -s $(which zsh)
	sudo apt install -y cargo 
	yes | cago install exa

    echo -e "${GREEN}installing ohmyzsh${ENDCOLOR}"
	sudo apt install -y curl
	echo $pass\n | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh RUNZSH='no')" 
	cp $HOME/dotFiles/.zshrc $HOME
	# zsh plugins
	sudo apt install -y autojump
	cd $HOME/Installs
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
	# p10k configure
	cd $HOME
    '

	# nala
    echo -e "${GREEN}installing nala${ENDCOLOR}"
	echo "deb http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
	wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
	sudo apt -y update
	if [[cat /etc/os-release | grep VERSION="2*" == "VERSION=\"22.*\""]]; then
		sudo apt install -y nala
	else
		sudo apt install -y nala-legacy
	fi

	#Latex
    echo -e "${GREEN}installing Latex${ENDCOLOR}"
	echo | sudo nala install -y latexmk zathura

	# firefox, ranger, nvim, flameshot
    echo -e "${GREEN}installing firefox, ranger, nvim, flameshot${ENDCOLOR}"
	echo | sudo nala install firefox ranger neovim flameshot
	ranger --copy-config=all

	mkdir $HOME/.config/nvim
	cp $HOME/dotFiles/init.vim $HOME/.config/nvim/
	# vim-plug
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

	# Discord
    echo -e "${GREEN}installing Discord${ENDCOLOR}"
	cd $HOME/Installs
	wget -O $HOME/Installs/discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
	echo | sudo nala install ./discord.deb
	cd $HOME

	# vscode
    echo -e "${GREEN}installing VScode${ENDCOLOR}"
	cd $HOME/Installs
	echo | sudo nala install software-properties-common apt-transport-https wget
	wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
	sudo add-apt-repository -y "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
	sudo apt install -y code
	cd $HOME

	# git ssh
    echo -e "${GREEN}configring git ssh${ENDCOLOR}"
	echo -ne '\n\n\n' | ssh-keygen -t ed25519 -C "anthonynmui@gmail.com"
	if [[!eval "$(ssh-agent -s)"]]; then
		echo error with ssh
		exit
	fi
	ssh-add ~/.ssh/id_ed25519

	# timeshift
    echo -e "${GREEN}installing timeshift${ENDCOLOR}"
	echo | sudo nala install timeshift
	git clone https://github.com/wmutschl/timeshift-autosnap-apt.git /home/$USER/Installs/timeshift-autosnap-apt
	cd /home/$USER/Installs/timeshift-autosnap-apt
	sudo make install
	cd $HOME
	
	echo \n installation done!
}

fedora_install () {
	read -n1 -p "install? [Y,n]" doit
	if [[$doit == 'y' || $doit =='Y']]; then
		echo starting install
	else
		exit
	fi
}

arch_install () {
	read -n1 -p "install? [Y,n]" doit
	if [[$doit == 'y' || $doit =='Y']]; then
		echo starting install
	else
		exit
	fi
}

echo select which distro
read -p '1:debian 2:fedora 3:arch ' distro

case $distro in  
  1) deb_install ;; 
  2) fedora_install ;; 
  3) arch_install ;;
  *) echo not a valid input ; exit;
esac

echo ===================================================================
echo do timshift, kitty font, btop, teams, ranger, vscode sign in, git add ssh, and user.email and user.name, clone personal files, nvim run:pluginstall, firefox plugin configs
echo add ssh key to git
echo NOTE: run the zsh script second
cat ~/.ssh/id_ed25519.pub
