#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

deb_install () {
	# echo installing git, kitty, zsh, nala, firefox, nvim, Latex, Discord, ranger, flameshot, timeshift
    read -p "install? [Y/n] " doit
    if [[ $doit = '' || $doit = 'y' || $doit = 'Y' ]]; then
        echo starting install...
    else
        echo exit
        exit
    fi


	# basic startup
    echo -e "${GREEN}==deb install==${ENDCOLOR}"

	cd ubuntu

	./install.sh

	yes | sudo nala install --install-recommends linux-generic-hwe-22.04

	#PPA

	##Neovim
	# yes | sudo add-apt-repository ppa:neovim-ppa/stable
	# yes | sudo apt update
	# yes | sudo apt install neovim

	#---Sound(Pipewire)---
	echo "---set sound---"
	yes | sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
	yes | sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream
	yes | sudo nala update
	yes | sudo nala install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,jack,alsa,v4l2,libcamera,locales,tests}} \
	libpipewire-module-x11-bell \
	wireplumber{,-doc} gir1.2-wp-0.4 libwireplumber-0.4-{0,dev} 
	yes | sudo nala install --no-install-recommends pavucontrol pulseaudio-utils

	./flatpak.sh
	# ./advanced.sh

	cd ..

	./dotinstall.sh

	echo "still need to manualy run autorandr -s <name>
	then 
	1. place this script (or better symlink it from autorandr location)
		to ~/.config/autorandr/postswitch
	2. run "nitrogen" and set wallpapers for current profile as you wish
	3. run ~/.config/autorandr/postswitch savebg
	4. repeat steps 2-3 for any profile you wish"

	echo " to change gtk theme: https://wiki.archlinux.org/title/GTK#Configuration"
}

fedora_install () {
	read -n1 -p "install? [Y,n]" doit
    if [[ $doit = '' || $doit = 'y' || $doit = 'Y' ]]; then
    	echo -e "${GREEN}==deb install==${ENDCOLOR}"
	else
		exit
	fi
	cd fedora
	bash fedora_install.sh

	cd ..

	./dotinstall.sh
}

arch_install () {
	read -n1 -p "install? [Y,n]" doit
	if [[$doit == 'y' || $doit =='Y']]; then
		echo starting install
	else
		exit
	fi
}

echo select which distro
read -p '1:debian 2:fedora 3:arch ' distro

case $distro in  
  1) deb_install ;; 
  2) fedora_install ;; 
  3) arch_install ;;
  *) echo not a valid input ; exit;
esac

echo ===================================================================
echo do timshift, kitty font, btop, teams, ranger, vscode sign in, git add ssh, and user.email and user.name, clone personal files, nvim run:pluginstall, firefox plugin configs
