context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Focusrite Scarlett 2i2 (Left channel mono)"
            capture.props = {
                node.name = "capture.Focusrite_Scarlett_2i2_Front_Left"
                audio.position = [ FL ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Focusrite_Scarlett_2i2_USB_Y84GA6V22DBD27-00.analog-stereo"
                node.passive = true
            }
            playback.props = {
                node.name = "Focusrite_Scarlett_2i2_Front_Left"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
]

